ロードマップAPIの作成
reciperu/reciperu-api-app pull request #20
Opened 2024-02-09 05:39 UTC by ryota0222

- microcmsで設定したデータを取得して返す
- env情報の追加（MICROCMS_API_KEY）

2024-02-09 15:12 UTC, masatotezuka requested changes
実装で気になった部分はとりあえずコメントした！

2024-02-09 15:12 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +    try {
サーバーエラーならtrycatchはいらないかな！
main.tsの`  app.useGlobalFilters(new HttpExceptionFilter());`でエラーはキャッチできるようにしているので！

2024-02-09 15:12 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +    private readonly loginUseCase: UseCaseProxy<LoginUseCase>,
これどこでつかっているの？

2024-02-10 01:11 UTC, ryota0222 commented on src/controllers/roadmap/roadmap.controller.ts
> +    try {
おけ！修正しました！

2024-02-10 01:12 UTC, ryota0222 commented on src/controllers/roadmap/roadmap.controller.ts
> +    private readonly loginUseCase: UseCaseProxy<LoginUseCase>,
ここのリストのデータをmicrocmsで登録しておいて、アプリの申請をせずに中のデータを変更できるようにしてる！

![CleanShot 2024-02-10 at 10 12 10](https://github.com/reciperu/reciperu-api-app/assets/45546517/3839276b-5aa5-492f-bb34-fac8c77d61dc)

2024-02-10 15:06 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +    private readonly loginUseCase: UseCaseProxy<LoginUseCase>,
あ、ごめん。loginUseCaseのこと！
LoginUseCaseの中のexecuteメソッドが呼ばれていないから、たぶん使われていないんじゃないかな？

2024-02-10 15:06 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +    private readonly loginUseCase: UseCaseProxy<LoginUseCase>,
firebaseの認証機能使うの？

2024-02-11 13:42 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.presenter.ts
> +  constructor(roadmap: Roadmap) {
これが不要
```ts
constructor(roadmap: Roadmap) {
    this.id = roadmap.getId;
    this.createdAt = roadmap.getCreatedAt;
    this.updatedAt = roadmap.getUpdatedAt;
    this.publishedAt = roadmap.getPublishedAt;
    this.revisedAt = roadmap.getRevisedAt;
    this.title = roadmap.getTitle;
    this.description = roadmap.getDescription;
    this.status = roadmap.getStatus;
  }
```

2024-02-11 13:44 UTC, masatotezuka requested changes

2024-02-11 13:44 UTC, masatotezuka commented on src/domain/roadmap.ts
このファイルも不要

2024-02-11 13:46 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +  async getRoadmap(@Req() req: Request) {
```suggestion
  async getRoadmap() 
```

2024-02-11 13:47 UTC, masatotezuka commented on src/controllers/roadmap/roadmap.controller.ts
> +    description: 'ロードマップ',
```suggestion
    description: 'ロードマップ'を取得する,
```

2024-02-11 13:50 UTC, masatotezuka approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8244662)

2024-02-11 13:53 UTC, merged