firebaseへの画像アップロード周りの機能追加
reciperu/reciperu-api-app pull request #24
Opened 2024-07-05 12:03 UTC by ryota0222

## What's changed

firebaseにユーザーの画像とレシピの画像をアップロードする機能を追加しました
- firebaseの初期化時にストレージ情報を追加
- DBのuserテーブルとrecipeテーブルに画像のファイル名を保存するカラムを追加
- ユーザーの新規登録、ユーザー情報変更時に、アイコンに変更があればstorageにアップロードするように変更

## Todo or Discussion
- [ ] /authですでにユーザーがいないかチェックしなくて良い？

2024-07-10 15:46 UTC, masatotezuka requested changes
`execute`メソッドで長い処理はかかずに、極力プライベートメソッドで定義して、そのメソッドを呼ぶ感じの実装にしてほしです！

2024-07-10 15:46 UTC, masatotezuka commented on prisma/migrations/20240704022653_add_filename_to_user/migration.sql
`db push`のほうに戻せそうなら戻してほしいです！

resetしないといけないかも？
https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production#reset-the-development-database

2024-07-10 15:46 UTC, masatotezuka commented on src/functions/image.ts
ここのメソッドはfirebaseServiceに持たせたいな。

2024-07-10 15:46 UTC, masatotezuka commented on src/use-cases/create-recipe.use-case.ts
> +    if (createRecipesDto.thumbnailUrl.length) {
このへんの処理はprivateメソッドに定義してほしい！

2024-07-10 15:46 UTC, masatotezuka commented on src/use-cases/create-recipes.use-case.ts
> +        if (x.thumbnailUrl.length) {
ここもprivateメソッドに定義してほしい！

2024-07-10 15:46 UTC, masatotezuka commented on src/use-cases/login.use-case.ts
> +    if (picture?.length) {
ここも処理はprivateメソッドに定義してほしい！

2024-07-11 04:22 UTC, ryota0222 commented on prisma/migrations/20240704022653_add_filename_to_user/migration.sql
done!
https://supabase.com/dashboard/project/vdubnxeoiybgsgcxvidj/editor/29429

2024-07-11 05:20 UTC, ryota0222 commented on src/functions/image.ts
firebase.serviceに移しましたー

2024-07-11 05:21 UTC, ryota0222 commented on src/use-cases/create-recipe.use-case.ts
> +    if (createRecipesDto.thumbnailUrl.length) {
done!

2024-07-11 05:21 UTC, ryota0222 commented on src/use-cases/create-recipes.use-case.ts
> +        if (x.thumbnailUrl.length) {
done!

2024-07-11 05:21 UTC, ryota0222 commented on src/use-cases/login.use-case.ts
> +    if (picture?.length) {
done!

2024-07-11 08:12 UTC, masatotezuka approved these changes

2024-07-11 15:19 UTC, merged