招待コードを短くする
reciperu/reciperu-api-app pull request #29
Opened 2024-07-09 08:16 UTC by ryota0222

以下の変更を行いました。
- 招待コードを生成前に、同じスペースに期限内の招待コードがないかを確認し、存在した場合はそのコードを返すように修正
- トークン生成APIのレスポンスに有効期限（`expiredAt`）を追加
- トークンを６桁に変更

2024-07-10 15:40 UTC, masatotezuka requested changes
処理は問題ないと思うけど、変更して欲しい箇所あるのでRequest changesにしておきます〜

2024-07-10 15:40 UTC, masatotezuka commented on src/domain/space.ts
> +    this.token = nanoid(6);
`await`必要ないの？
```suggestion
    this.token = await nanoid(6);
```

2024-07-10 15:40 UTC, masatotezuka commented on src/infrastructure/database/prisma/repositories/prisma.space-invitation.repository.ts
> +    const prismaInvitation = prismaInvitations.find(
repository層はデータの取得・更新だけの責務にしたいから、この処理はusecase層でやりたいな〜

2024-07-10 15:40 UTC, masatotezuka commented on src/infrastructure/database/prisma/repositories/prisma.space-invitation.repository.ts
> +  async findValidSpaceInvitation(
こっちのほうが他のメソッドど統一性がとれるかな
```suggestion
  async findSpaceInvitationsBySpaceId(
```

2024-07-10 15:40 UTC, masatotezuka commented on src/use-cases/invite-space.use-case.ts
> +      );
repository層から配列で取得して、有効なInvitationはこっちで取得したい
```ts
const prismaInvitation = prismaInvitations.find(
      // 有効期限が切れていない招待を取得
      (invitation) => invitation.expiredAt > new Date(),
    );
```

有効期限が切れていない招待を取得するメソッドはdomain層に書いた方がいいかもな

2024-07-11 03:47 UTC, ryota0222 commented on src/domain/space.ts
> +    this.token = nanoid(6);
nanoidは非同期じゃないので、asyncの方が間違いやった！ので削除しといたー
```
  generateToken(): void {
    this.token = nanoid(6);
  }
```

2024-07-11 03:47 UTC, ryota0222 commented on src/use-cases/invite-space.use-case.ts
> +      );
こちら対応していますー！
https://github.com/reciperu/reciperu-api-app/pull/29/commits/feaf8239ecdf09eea6bfc66dc674cfe8be8c9f70

2024-07-11 08:10 UTC, masatotezuka requested changes

2024-07-11 08:10 UTC, masatotezuka commented on src/use-cases/invite-space.use-case.ts
> +    await spaceInvitationBeforePersist.generateToken();
generateだと値が返ってくると想定するから、setTokenのほうがよさそう
あと、await不要かな？
```suggestion
   spaceInvitationBeforePersist.setToken();
```

2024-07-11 08:10 UTC, masatotezuka commented on src/infrastructure/database/prisma/repositories/prisma.space-invitation.repository.ts
> +  async findValidSpaceInvitationsBySpaceId(
変更お願いします！
```suggestion
  async findSpaceInvitationsBySpaceId(
```

2024-07-11 09:29 UTC, ryota0222 commented on src/use-cases/invite-space.use-case.ts
> +    await spaceInvitationBeforePersist.generateToken();
ほんとソーリー
修正します！

2024-07-11 09:44 UTC, ryota0222 commented on src/use-cases/invite-space.use-case.ts
> +    await spaceInvitationBeforePersist.generateToken();
setTokenが他で使われてたから`generateAndSetToken`に変更したー
```
generateToken(): void {
    this.token = nanoid(6);
  }
 set setToken(token: string) {
    this.token = token;
 }
```

2024-07-11 11:03 UTC, masatotezuka approved these changes
LGTM

2024-07-11 15:18 UTC, merged